---
name: "Devel (nightly) Release"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
permissions:
  contents: "write"
  packages: "write"
env:
  GO_VERSION: "~1.19.4"
jobs:
  goreleaser:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - uses: "actions/setup-go@v3"
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: "true"
      - uses: "authzed/actions/docker-login@main"
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"
      - uses: "goreleaser/goreleaser-action@v3"
        with:
          distribution: "goreleaser-pro"
          version: "latest"
          args: "release --clean --nightly"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
